---

  - name: "add repository for modern redis"
    sudo: true
    apt_repository: >
      repo='ppa:chris-lea/redis-server'
      state=present

  - name: install redis
    sudo: true
    apt: pkg=redis-server state=present update_cache=yes
