---
  - name: download node
    get_url: >
      url=http://nodejs.org/dist/v{{npme_node_version}}/node-v{{npme_node_version}}.tar.gz
      dest="{{npme_home_directory}}/node-v{{npme_node_version}}.tar.gz"

  - name: build
    sudo: true
    command: "{{item}}"
    with_items:
      - "tar -xvf node-v{{npme_node_version}}.tar.gz chdir={{npme_home_directory}}"
      - "./configure chdir={{npme_home_directory}}/node-v{{npme_node_version}}"
      - "make chdir={{npme_home_directory}}/node-v{{npme_node_version}}"
      - "make install chdir={{npme_home_directory}}/node-v{{npme_node_version}}"

  - name: remove node tarball
    file: >
      path="{{npme_home_directory}}/node-v{{npme_node_version}}.tar.gz"
      state=absent
