---
  # copy configuration to location, post install.
  # this is split into two steps, because we
  # interview the user about environment variables
  # in-between.
  - name: copy nginx configuration
    sudo: true
    notify: 'restart nginx'
    template: >
      src=nginx.conf.j2
      dest=/etc/nginx/nginx.conf
      owner={{npme_owner}}
      group={{npme_group}}
      mode=770

  - name: copy couchdb configuration
    sudo: true
    notify: 'restart couchdb'
    copy: >
      src=local.ini
      dest=/etc/couchdb/local.ini
      owner={{npme_couchdb_owner}}
      group={{npme_couchdb_group}}
      mode=770
